85 documentation/adicionar diagrama de pacotes
UnBArqDsw2022-1/2022.1_G4_FluxoAgil pull request #124
Opened 2022-07-15 00:37 UTC by gatotabaco

Esse PR contém o documento "diagrama componentes". 

## Types of changes

What types of changes does your code introduce to <repo_name>?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the CONTRIBUTING.md doc.
- [x] I have added necessary documentation (if appropriate).
- [x] Any dependent changes have been merged and published in downstream modules.

2022-07-15 00:44 UTC, Thais-ra commented on docs/Modelagem/UMLEstaticos/diagrama_pacotes.md
> +Inicialmente os participantes realizaram um estudo prévio acerca do conteúdo, depois foi realizada uma reunião no discord para poder criar o diagrama. Os integrantes decidiram utilizar o lucidchart p
Tem um erro em "assíncrona" no final do texto.

2022-07-15 00:45 UTC, Thais-ra commented on docs/Modelagem/UMLEstaticos/diagrama_pacotes.md
> +Inicialmente os participantes realizaram um estudo prévio acerca do conteúdo, depois foi realizada uma reunião no discord para poder criar o diagrama. Os integrantes decidiram utilizar o lucidchart p
Colocar "Telegram" com T maiúsculo.

2022-07-15 00:46 UTC, Thais-ra reviewed
Não esqueçam de atualizar o nome dos revisores.

2022-07-15 01:39 UTC, yudi-azvd requested changes
Sobre o diagrama: 

1 - o que é o pacote App? é a interface com o usuário? Se sim pq existem dois Apps? Acho que deveria ser apenas um. Ou, talvez, nenhum pq o fronted meio que já é a GUI.

2 - a seta é o relacionamento mais genérico que significa dependência. Se A -> B, então A depende de B (note o sentido da seta). Com isso em mente, reveja os sentidos das setas nos pacotes dentro de Frontend e de Backend, eles estão invertidos.

Dê uma olhada em https://www.uml-diagrams.org/package-diagrams-overview.html.

O Frontend não depende do Backend. É o contrário.

O SIGAA não depende do Scrapper. O Scrapper depender do banco de dados acho que está certo.

2022-07-15 02:52 UTC, merged

2022-07-22 17:00 UTC, yudi-azvd commented
Só pra deixar registrado, fui corrigido dos meus erros. Devia estar cansado e confundi a dependência do front-end e backend. Mals, familia xD