168 docs/gofs criacional
UnBArqDsw2022-1/2022.1_G4_FluxoAgil pull request #178
Opened 2022-08-12 21:38 UTC by mateusmaiamaia

Documentação do padrão de projeto singleton

## Types of changes

- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the CONTRIBUTING.md doc.
- [ ] I have added necessary documentation (if appropriate).
- [ ] Any dependent changes have been merged and published in downstream modules...

2022-08-12 23:00 UTC, AnaCarolinaRodriguesLeite requested changes

2022-08-12 23:05 UTC, matheuscvp commented on docs/PadroesDeProjeto/gof-singleton-pattern.md
> +Este código não foi implementado, ele servirar como base para a criação do banco de dados do scraper, que será utilizado para pegar os dados das disciplinas dos cursos da Universidade de Brasília.
sim, a palavra scraper está certa.

2022-08-13 01:13 UTC, lbvx requested changes

2022-08-13 01:13 UTC, lbvx commented on docs/PadroesDeProjeto/gof-criacional.md
> +|            |        |                      |                                                   |            |
Tem uma linha vazia na tabela e faltou adicionar o(s) revisor(es).

2022-08-13 01:25 UTC, lbvx approved these changes

2022-08-13 02:49 UTC, merged