Guia de estilo
UnBArqDsw2022-1/2022.1_G4_FluxoAgil pull request #45
Opened 2022-06-25 18:59 UTC by matheuscvp

Documento referente ao Guia de estilo a ser utilizado no projeto

## Checklist
- [ ] Guia de estilo feito corretamente
- [ ] Guia de estilo estar de acordo com as escolhas do grupo
- [ ] Guia de estilo estar englobando todas as cores a serem utilizadas no projeto

## Issue
#43

2022-06-25 21:08 UTC, mateusmaiamaia requested changes

2022-06-25 21:08 UTC, mateusmaiamaia commented on docs/Base/AbordagemNaoEspecifica/guiaDeEstilo.md
> +# Guia de Estilo
Os arquivos estão todos certos, mas está faltando adicionar o caminho no __sidebar.md

2022-06-26 16:00 UTC, irwinschmitt requested changes
Seria interessantes a especificação das fontes em diferentes contextos, com `font`, `weight`, `size` e `spacing`, como em:

https://vuetifyjs.com/en/styles/text-and-typography/#typography
https://getbootstrap.com/docs/4.0/content/typography/#headings 
https://ant.design/components/typography

2022-06-27 21:49 UTC, irwinschmitt requested changes
Adicionar link na página de iniciativas extras.

2022-06-27 21:59 UTC, matheuscvp commented
Adicionado o Link na página de Iniciativas Extras

2022-06-27 23:31 UTC, irwinschmitt approved these changes

2022-06-28 00:17 UTC, merged